# Understanding NUMPY

### Numpy is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [1]:
import numpy as np

## Arrays

In [2]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])

In [3]:
print(type(a))
print(a.shape)
print(type(b))
print(b.shape)

<class 'numpy.ndarray'>
(3,)
<class 'numpy.ndarray'>
(2, 3)


In [4]:
# Creates a 2X2 zeros array 
c=np.zeros((2,2))
c

array([[0., 0.],
       [0., 0.]])

In [5]:
# Creates a 2X4 ones array
d=np.ones((2,4))
d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
# Create a 2X2 constant array
e = np.full((2,2), 7)  
e

array([[7, 7],
       [7, 7]])

In [7]:
# Creates a 3X3 identity matrix
f = np.eye(3)       
f 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
# Create a 3X2 array filled with random values
g = np.random.random((3,2))  
g

array([[0.92981109, 0.65623383],
       [0.25618268, 0.1946616 ],
       [0.39159853, 0.99707112]])

In [9]:
# Creates a range of elements till 7
h = np.arange(7)
h

array([0, 1, 2, 3, 4, 5, 6])

## Slicing

In [10]:
# b is the sub array consisting of the first 2 rows and columns 1 and 2 of array a
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2, 1:3]
print(b)

# A slice of an array is a view into the same data, so modifying it will modify the original array.
print(a[0, 1])   
b[0, 0] = 77     # b[0, 0] is the same piece of data as a[0, 1]
print(a[0, 1])

[[2 3]
 [6 7]]
2
77


## Adding and removing the elements

In [11]:
# adds 1,2,3,4 at the end
a = [0]
a = np.append(a, [1,2,3,4]) 
print(a)

[0 1 2 3 4]


In [12]:
# Deletes elements 2 and 3 from the array
a = np.delete(a, [2,3]) 
print(a)

[0 1 4]


## Sorting the array

In [13]:
# To sort an array, the sort (array, axis, kind, orderby) function is used
a = np.array([[3,2,1],[6,5,4],[9,8,7]])
print(a)
a = np.sort(a, axis=1, kind = 'quicksort')
print(a)

[[3 2 1]
 [6 5 4]
 [9 8 7]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Major functions and attributes

In [14]:
# Reshaping
a = np.arange(10)
print(a)
a = a.reshape(2,5)
a

[0 1 2 3 4 5 6 7 8 9]


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
# Concatenate - Arrays are joined on the basis of their axis
b = [1,2]
c = [3,4]
d=[b,c]
d = np.concatenate(d)
print(d)

[1 2 3 4]


Large number of string operations are also available like lower(),upper(),replace()

In [16]:
# Mathematical Functions
e = np.add(b,c)
print(e)
f = np.subtract(b,c)
print(f)
g = np.multiply(b,c)
print(g)
h = np.divide(b,c)
print(h)
i = np.power(b,c) 
print(i)

[4 6]
[-2 -2]
[3 8]
[0.33333333 0.5       ]
[ 1 16]
