In [1]:
import numpy as np

In [2]:
my_lst = [1,2,3,4,5]
arr = np.array(my_lst)

In [3]:
type(arr)

numpy.ndarray

In [4]:
arr

array([1, 2, 3, 4, 5])

In [5]:
arr.shape

(5,)

In [6]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [7]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [8]:
arr.shape

(3, 5)

In [9]:
arr.reshape(5,3)

array([[1, 2, 3],
       [4, 5, 2],
       [3, 4, 5],
       [6, 9, 7],
       [6, 8, 9]])

## Indexing

In [10]:
## Accessing the array elements
arr=np.array([1,2,3,4,5,6,7,8,9])

In [11]:
arr[3]

4

In [12]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]
arr=np.array([my_lst1,my_lst2,my_lst3])

In [14]:
arr[1:,3:]

array([[5, 6],
       [8, 9]])

## Inbuild functions

In [15]:
## arr[row_start:row_end+1,col_start:col_end+1,step]
arr=np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#between 1 & 10-> it will print 50 pts
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [17]:
## copy function & broadcasting
arr[3:]=100

In [18]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

## Reference type

In [19]:
arr1=arr

In [20]:
arr1[3:]=500
print(arr1)
print(arr)

[  0   1   2 500 500 500 500 500 500 500]
[  0   1   2 500 500 500 500 500 500 500]


In [21]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [22]:
## copy
arr1=arr.copy()
print(arr)

[  0   1   2 500 500 500 500 500 500 500]


In [37]:
arr1[3:]=1000
print(arr1)
print(arr)

[   0    1    2 1000 1000 1000 1000 1000 1000 1000]
[  0   1   2 500 500 500 500 500 500 500]


In [25]:
val=2
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [26]:
arr*2

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [27]:
arr%2

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [28]:
## to get exact numbers less than 2
arr[arr<2]

array([0, 1])

In [29]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [38]:
np.ones(4)

array([1., 1., 1., 1.])

In [31]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [32]:
np.ones((2,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

## Random distribution

In [33]:
np.random.rand(3,3)

array([[0.44571676, 0.66351677, 0.64235836],
       [0.80969753, 0.05029753, 0.48395202],
       [0.67939213, 0.13872941, 0.99104406]])

In [40]:
arr_ex=np.random.randn(4,4)
arr_ex

array([[-0.11247032, -0.16282973,  1.39063458, -0.28930299],
       [-0.61463374, -0.4087743 , -0.18336918,  0.04973517],
       [ 0.80441201,  1.62111082, -0.93408142,  1.0513835 ],
       [-1.3073208 , -1.97930705,  0.25200628, -0.61573328]])

In [41]:
np.random.randint(0,100,8)

array([73, 16, 46, 18,  6, 77, 51, 67])

In [36]:
np.random.random_sample((1,5))

array([[0.33593498, 0.34104769, 0.39807455, 0.51159609, 0.31665082]])