
# **NumPy (Numerical Python)**

In [ ]:
import numpy as np


In [ ]:
a=np.zeros(3)
a

array([0., 0., 0.])

In [ ]:
type(a)

numpy.ndarray

In [ ]:
a.ndim

1

In [ ]:
list(a)

[0.0, 0.0, 0.0]

In [ ]:
a.shape

(3,)

In [ ]:
a.size

3

In [ ]:
a.shape=(3,1)
a

array([[0.],
       [0.],
       [0.]])

In [ ]:
a.ndim , a.shape,a.size

(2, (3, 1), 3)

In [ ]:
a.reshape(3,1)
a

array([[0.],
       [0.],
       [0.]])

In [ ]:
b=25
c=np.sqrt(b)
c

5.0

In [ ]:
np.random.seed(18)
q=np.random.randint(1,20,[5,5])
q

array([[11,  6, 18, 15, 19],
       [ 3,  9,  3, 18,  6],
       [16, 11, 11, 12,  5],
       [ 5, 12,  2,  4, 10],
       [ 6, 15,  7, 14,  9]])

In [ ]:
w=np.argsort(q)
w

array([[1, 0, 3, 2, 4],
       [0, 2, 4, 1, 3],
       [4, 1, 2, 3, 0],
       [2, 3, 0, 4, 1],
       [0, 2, 4, 3, 1]])

In [ ]:
q.shape , q.size , q.ndim

((5, 5), 25, 2)

In [ ]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [ ]:
np.arange(18)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
x=[1,2,3,4,5,6,7,8,9]
x

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
y=np.array(x)
y

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
j=np.random.randint(4,60,(4,5))
j

array([[22,  4, 33, 13, 17],
       [14, 17, 19,  7, 54],
       [32,  7, 35, 25, 15],
       [46, 59, 38, 29, 33]])

In [ ]:
k=np.random.randint(4,50,(4,5))
k

array([[26, 29,  7, 39, 25],
       [45, 30, 39, 42, 15],
       [13, 36, 31, 48, 32],
       [38, 17,  9, 18, 23]])

In [ ]:
l=j-k
l

array([[ -4, -25,  26, -26,  -8],
       [-31, -13, -20, -35,  39],
       [ 19, -29,   4, -23, -17],
       [  8,  42,  29,  11,  10]])

In [ ]:
m=j+k
m

array([[48, 33, 40, 52, 42],
       [59, 47, 58, 49, 69],
       [45, 43, 66, 73, 47],
       [84, 76, 47, 47, 56]])