In [63]:
import numpy as np

from collections import Counter

In [64]:
from sklearn import datasets

In [65]:
iris = datasets.load_iris()

In [66]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target,random_state = 2, test_size=0.25)

In [67]:
def fit(X,y):        ### KNN first store the training data
    X_train=X
    y_train=y

In [68]:
def distance (X_1,X_2):         ### this is how we find eucleadin distance , in this we find the distance bw training data as X1 and testing data as X2
    distance= np.sqrt(np.sum((X_1-X_2)**2))
    return distance

In [69]:
def predict(X_test,k):          ## we define a predict function with X-test data to be predicted 
    output=[]
    for i in range(len(X_test)):
        d=[]           ### we take a empty list "d" and append the ,distance bw X_train and X_test with index of training data i.e., "j", in list .
        votes=[]
        for j in range(len(X_train)):   
            dist= np.sqrt(np.sum((X_train[j]-X_test[i])**2))
            d.append([dist,j])
        d.sort()            ## we sort the data with increasing distance
        d=d[0:k]            ## among the list having distances , we choose the nearest one upto k values (If we choose 3 that means 3 nearest neigbors of test_data  )
        for d,j in d :     ## for distaces and indexes in list d
            votes.append(y_train[j])
        ans=Counter(votes).most_common(1)[0][0]        ## First counter method will count the each values and then it selectt that occur more times and then select the particular distance .
        output.append(ans)
    return output


In [70]:

print(predict(X_test,k=3))

[0, 0, 2, 0, 0, 2, 0, 2, 2, 0, 0, 0, 0, 0, 1, 1, 0, 1, 2, 1, 1, 1, 2, 1, 1, 0, 0, 2, 0, 2, 2, 0, 1, 2, 1, 0, 2, 1]


In [71]:

def score(X_test,y_test,k):
    prediction=predict(X_test,k)
    return (prediction==y_test).sum()/len(y_test)

In [72]:
score(X_test,y_test,3)

1.0

info about counter

In [73]:
a=[[101,1],[1235,2],[1455,4],[17,3],[211,5]]
a[0:4]

[[101, 1], [1235, 2], [1455, 4], [17, 3]]

In [ ]:
a.append([11,55])

In [ ]:
a

[[101, 1], [1235, 2], [1455, 4], [17, 3], [211, 5], [11, 55]]

In [ ]:
a.sort()

In [81]:
a

[[101, 1], [1235, 2], [1455, 4], [17, 3], [211, 5]]

In [84]:
b=[1,2,4,5,5,6,5,5,8,4,6,8,7,9,5,4,3,2,5,65,5,8,7,7,6,1,7,3,7,7,5,7,7,5]

In [87]:
f=[]
for i, j in a :
    f.append(b[j])            
f

[2, 4, 5, 5, 6]

In [89]:
Counter(f)

[(5, 2)]

In [91]:
Counter(f).most_common(1)

[(5, 2)]

In [39]:
Counter(b)

Counter({1: 3, 2: 2, 3: 2, 4: 3, 5: 8, 6: 3, 7: 8, 8: 3, 9: 1, 65: 1})

In [40]:
Counter(b).most_common(1)

[(5, 8)]

In [ ]:
Counter(b).most_common(1)[0][0]

5

In [ ]:
Counter?

In [ ]:
>>> c = Counter('abcdeabcdabcaba')  # count elements from a string

>>> c.most_common(3)                # three most common elements
[('a', 5), ('b', 4), ('c', 3)]
>>> sorted(c)                 


In [ ]:
>>> c = Counter('abcdeabcdabcaba')  # count elements from a string

>>> c.most_common(3)                # three most common elements
[('a', 5), ('b', 4), ('c', 3)]
>>> sorted(c)                 

In [78]:
type(X_train)

numpy.ndarray

KNN WITH CLASS

In [23]:
class KNN:
    def __init__(self, k):          ### INITIALIZATION
        self.k = k
        
    def fit(self, X, y):            ### KNN first store the training data
        self.X_train = X
        self.y_train = y
        
    ## def distance(self, X1, X2):         ### this is how we find eucleadin distance , in this we find the distance bw training data as X1 and testing data as X2
       ### distance = np.sqrt(np.sum((X1-X2)**2))

    def predict(self, X_test):             ## we define a predict function with X-test data to be predicted 
        final_output = []                   
        for i in range(len(X_test)):           ### we take a empty list "d" and append the ,distance bw X_train and X_test with index of training data i.e., "j", in list .
            d = []
            votes = []
            for j in range(len(X_train)):
                dist = np.sqrt(np.sum((X_train[j] - X_test[i])**2))
                d.append([dist, j])
            d.sort()                                ## we sort the data with increasing distance
            d = d[0:self.k]                         ## among the list having distances , we choose the nearest one upto k values (If we choose 3 that means 3 nearest neigbors of test_data  )
            for d, j in d:                          ## for distaces and indexes in list d
                votes.append(y_train[j])            
            ans = Counter(votes).most_common(1)[0][0]     ## First counter method will count the each values and then it selectt the most common 1 and then select the particular distance .
            final_output.append(ans)
            
        return final_output
    
    def score(self, X_test, y_test):
        predictions = self.predict(X_test)
        return (predictions == y_test).sum() / len(y_test)

In [24]:
clf = KNN(3)
clf.fit(X_train, y_train)
prediction = clf.predict(X_test)
for i in prediction:
    print(i, end= ' ')

0 0 2 0 0 2 0 2 2 0 0 0 0 0 1 1 0 1 2 1 1 1 2 1 1 0 0 2 0 2 2 0 1 2 1 0 2 1 

In [61]:
prediction == y_test

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [8]:
clf.score(X_test, y_test)

1.0

In [93]:
X_train[0:5]

array([[5.5, 2.3, 4. , 1.3],
       [6.9, 3.1, 5.1, 2.3],
       [6. , 2.9, 4.5, 1.5],
       [6.2, 2.9, 4.3, 1.3],
       [6.8, 3.2, 5.9, 2.3]])

In [94]:
X_test[0:5]

array([[4.6, 3.4, 1.4, 0.3],
       [4.6, 3.1, 1.5, 0.2],
       [5.7, 2.5, 5. , 2. ],
       [4.8, 3. , 1.4, 0.1],
       [4.8, 3.4, 1.9, 0.2]])

In [96]:
y_train[0:5]

array([1, 2, 1, 1, 2])

In [98]:
y_test[0:5]

array([0, 0, 2, 0, 0])

In [99]:
X_train[0]

array([5.5, 2.3, 4. , 1.3])

In [100]:
X_test[0]

array([4.6, 3.4, 1.4, 0.3])

In [102]:
X_train[0]-X_test[0]

array([ 0.9, -1.1,  2.6,  1. ])

In [103]:
(X_train[0]-X_test[0])**2

array([0.81, 1.21, 6.76, 1.  ])

In [109]:
np.sum((X_train[0]-X_test[0])**2)

9.780000000000001