In [1]:
import numpy as np

In NumPy vectors are represented as n-dimensional arrays. To create a vector in R^3

In [3]:
x=np.array([[1],
           [2],
           [3]])

In [5]:
x.shape

(3, 1)

In [9]:
print('A 3-dimensional vector:\n{}'.format(x))

A 3-dimensional vector:
[[1]
 [2]
 [3]]


In NumPy, we add two vectors of the same with the + operator or the add method:



In [12]:
a = b = np.array([[10],
                  [20],
                  [30]])

In [13]:
a+b

array([[20],
       [40],
       [60]])

In NumPy, we compute scalar-vector multiplication with the * operator:

In [14]:
s=4
s*a

array([[ 40],
       [ 80],
       [120]])

In NumPy, we do linear combinations :

In [28]:
a,b=4,5
x,y=np.array([[1],[2]]),np.array([[2],[3]])

In [29]:
print("x:\n",x)
print("y:\n",y)

x:
 [[1]
 [2]]
y:
 [[2]
 [3]]


In [30]:
a*x + b*y

array([[14],
       [23]])

In [35]:
x.T@y #1x2 2x1 =1x1

array([[8]])

**In addition, vector addition and multiplication must follow these eight rules:**

commutativity: x+y=y+x 

associativity: x+(y+x)=(y+x)+z 

unique zero vector such that: x+0=x for all  x

for all x there is a unique vector x such that x+(−x)=0

identity element of scalar multiplication: 1x=x

distributivity of scalar multiplication w.r.t vector addition: x(y+z)=xz+zy

x(yz)=(xy)z

(y+z)x=yx+zx

In NumPy, we can compute the L2 norm as:


In [38]:
x = np.array([[3],[4]])
np.linalg.norm(x, 2)

5.0

L1 norm

In [39]:
x = np.array([[3],[-4]])
np.linalg.norm(x, 1)

7.0

In [40]:
A = np.array([[0,2],
              [1,4]])
B = np.array([[3,1],
              [-3,2]])
A+B

array([[ 3,  3],
       [-2,  6]])

In [41]:
A@B

array([[-6,  4],
       [-9,  9]])

In [42]:
A = np.array([[1, 2, 1],
              [4, 4, 5],
              [6, 7, 7]])


In NumPy, we can compute the inverse of a matrix :

In [43]:
A_i = np.linalg.inv(A)
print(f'A inverse:\n{A_i}')

A inverse:
[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


veryfying

In [45]:
np.round(A_i@A) # we get identity matrix

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [46]:
A.T

array([[1, 4, 6],
       [2, 4, 7],
       [1, 5, 7]])

matrix matrix multiplication

In [48]:
A = np.array([[0,2],
              [1,4]])
B = np.array([[1,3],
              [2,1]])
A*B

array([[0, 6],
       [2, 4]])

Consider this eqn. AX=Y , we hv to find X

In NumPy, we can solve a system of equations with Gaussian Eliminatioion.

In [49]:
A = np.array([[1, 3, 5],
              [2, 2, -1],
              [1, 3, 2]])
y = np.array([[-1],
              [1],
              [2]])

In [50]:
np.linalg.solve(A, y)

array([[-2.],
       [ 2.],
       [-1.]])