In [1]:
import numpy as np
import pandas as pd

In [2]:
array  = np.ones(4)

In [3]:
array

array([1., 1., 1., 1.])

In [4]:
i = np.identity(3)
i

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
array_a = np.array([[1,2],[3,4]])
array_b = np.array([[1,2],[3,4]])

In [7]:
dot_product = np.dot(array_a,array_b)
dot_product 

array([[ 7, 10],
       [15, 22]])

In [8]:
cross_product = np.cross(array_a, array_b)
cross_product

array([0, 0])

In [ ]:
In [26]: numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
In [27]: print(numpy_array.mean())
Out[27]: 5
In [28]: print(numpy_array.median())
Out[28]: 5
In [29]: print(numpy_array.var())
Out[29]: 6.666666666666667
In [30]: print(numpy_array.std())
Out[30]: 2.581988897471611

In [13]:
numpy_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
mean = numpy_array.mean()
variance = numpy_array.var()
standard_deviation = numpy_array.std()

In [16]:
print('Mean :',mean)
print('Variance:',variance)
print('Standard Deviation:', standard_deviation)

Mean : 5.0
Variance: 6.666666666666667
Standard Deviation: 2.581988897471611
