In [1]:
import pandas as pd
import numpy as np

In [4]:
dataset = pd.read_csv('sample - sample.csv')
dataset.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [5]:
dataset.isnull().sum()

Country      0
Age          1
Salary       1
Purchased    0
dtype: int64

In [6]:
x = dataset.iloc[:,:-1].values
y = dataset.iloc[:,3:].values


In [7]:
 from sklearn.impute import SimpleImputer

In [8]:
imp = SimpleImputer(missing_values = np.nan , strategy = 'mean')
x[:,1:3] = imp.fit_transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [10]:
from sklearn.preprocessing import LabelEncoder
LabEnc = LabelEncoder()
x[:,0] = LabEnc.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [12]:
y = LabEnc.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1], dtype=int64)

In [14]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [29]:
transform = ColumnTransformer([('norm1',OneHotEncoder(),[0])], remainder = 'passthrough')
x = transform.fit_transform(x)
x

array([[0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 1.0, 0.0, 50.0, 83000.0],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [30]:
from sklearn.model_selection import train_test_split

In [31]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [32]:
x_train

array([[1.0, 0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [0.0, 1.0, 0.0, 0.0, 37.0, 67000.0],
       [1.0, 0.0, 0.0, 1.0, 27.0, 48000.0],
       [1.0, 0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [0.0, 1.0, 0.0, 0.0, 48.0, 79000.0],
       [1.0, 0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 1.0, 0.0, 0.0, 35.0, 58000.0]], dtype=object)

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
St = StandardScaler()
x_train[:,3:5] = St.fit_transform(x_train[:,3:5])
x_train

array([[1.0, 0.0, 1.0, -0.7745966692414834, 0.2630675731713538,
        63777.77777777778],
       [0.0, 1.0, 0.0, -0.7745966692414834, -0.25350147960148617,
        67000.0],
       [1.0, 0.0, 0.0, 1.2909944487358056, -1.9753983221776195, 48000.0],
       [1.0, 0.0, 0.0, 1.2909944487358056, 0.05261351463427101, 52000.0],
       [0.0, 1.0, 0.0, -0.7745966692414834, 1.6405850472322605, 79000.0],
       [1.0, 0.0, 0.0, 1.2909944487358056, -0.08131179534387283, 61000.0],
       [0.0, 1.0, 0.0, -0.7745966692414834, 0.9518263102018072, 72000.0],
       [0.0, 1.0, 0.0, -0.7745966692414834, -0.5978808481167128, 58000.0]],
      dtype=object)